
   let products = [
    {
        id: 1,
        title: "Maths",
        location: "London",
        priceText: "Price: £ ",
        price:  100,
        spaces: "Number of spaces: ",
        spaceNumber: 5,
        image: "maths.png",
    },
    {
        id: 2,
        title: "Science",
        location: "Manchester",
        priceText: "Price: £ ",
        price: 150,
        spaces: "Number of spaces: ",
        spaceNumber: 10,
        image: "science.png",            
    },
    {
        id: 3,
            title: "Music",
            location: "Bristol",
            priceText: "Price: £ ",
            price: 200,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "music.png",
    },
    {
        id: 4,
            title: "English",
            location: "London",
            priceText: "Price: £ ",
            price: 75,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "english.png",
    },
    {
        id: 5,
            title: "Drama",
            location: "London",
            priceText: "Price: £ ",
            price: 350,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "drama.png",
    },
    {
        id: 6,
            title: "French",
            location: "Surrey",
            priceText: "Price: £ ",
            price: 180,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "french.png",
    },
    {
        id: 7,
            title: "Geography",
            location: "Essex",
            priceText: "Price: £ ",
            price: 100,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "geography.png",
    },
    {
        id: 8,
            title: "Art",
            location: "London",
            priceText: "Price: £ ",
            price: 100,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "art.png",
    },
    {
        id: 9,
            title: "History",
            location: "Surrey",
            priceText: "Price: £ ",
            price: 100,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "history.png",
    },
    {
        id: 10,
            title: "PE",
            location: "Watford",
            priceText: "Price: £ ",
            price: 100,
            spaces: "Number of spaces: ",
            spaceNumber: 5,
            image: "pe.png",
    }

]


